### ISSUE TITLE
Capbility Statement Version element not matching specification version

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/gpconnect-demonstrator#87] opened 2018-08-09 08:13 UTC
The demonstrator is now built to comply with the 1.2.0 version of the specification. The version number in the conformance statement needs to be 1.2.0 but it is 1.0.0 currently.

**Comment by jonnyry** [comment] 2018-09-28 07:33
Duplicate of #91 
Closing.

**Closed by jonnyry** 2018-09-28 07:33 UTC
Labels: bug, duplicate
