### ISSUE TITLE
Book appointment - description and comment field character limit handling

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-demonstrator#221] opened 2019-04-08 08:59 UTC
- Demonstrator should support storing the limits of 100 characters (description field) and 500 characters (comment field)
- Demonstrator should not truncate description or comment fields
- If a consumer sends more than the limits above, the demonstrator should return an error, suggested 422 / INVALID_RESOURCE

---

Release notes: https://gpconnect-1-2-3.netlify.com/overview_release_notes_1_2_3.html#book-appointment---description-and-comment-field-character-limit-handling-clarification
Spec ticket:  https://github.com/nhsconnect/gpconnect/issues/625
Demonstrator ticket: https://github.com/nhsconnect/gpconnect-demonstrator/issues/221
Provider test suite ticket:  https://github.com/nhsconnect/gpconnect-provider-testing/issues/203

**Comment by SimonFarrowNHS** [comment] 2019-04-08 12:45
AFAIK This is already implemented

**Comment by SimonFarrowNHS** [comment] 2019-04-08 12:48
See #123 and #124

**Comment by SimonFarrowNHS** [comment] 2019-04-12 12:35
Closed as a duplicate of #123 and #124

**Closed by SimonFarrowNHS** 2019-04-12 12:35 UTC
Labels: 1.2.3
